#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/input_output.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module input_output.yang


class ns(object):
    hash = 1866487254

    id = "http://example.com/input_output"

    uri = "http://example.com/input_output"

    prefix = "input_output"

    input_output_device = 1
    input_output_device_ = "device"
    input_output_csv = 2
    input_output_csv_ = "csv"
    input_output_device_group = 0
    input_output_device_group_ = "device_group"
