#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Object_group_cleaner.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Object_group_cleaner.yang


class ns(object):
    hash = 1323656690

    id = "http://example.com/tools"

    uri = "http://example.com/tools"

    prefix = "tools"

    tools_objet_group = 1025221416
    tools_objet_group_ = "objet_group"
    tools_input_type = 1878066786
    tools_input_type_ = "input_type"
    tools_Object_group_cleaner = 1167528207
    tools_Object_group_cleaner_ = "Object_group_cleaner"
    tools_orphaned_object_groups = 2086991772
    tools_orphaned_object_groups_ = "orphaned_object_groups"
    tools_csv = 2
    tools_csv_ = "csv"
    tools_run_time = 1050052059
    tools_run_time_ = "run_time"
    tools_device_group = 0
    tools_device_group_ = "device_group"
    tools_end_time = 102468597
    tools_end_time_ = "end_time"
    tools_value = 864367181
    tools_value_ = "value"
    tools_inputs = 428023244
    tools_inputs_ = "inputs"
    tools_search = 472086744
    tools_search_ = "search"
    tools_start_time = 361541635
    tools_start_time_ = "start_time"
    tools_remove = 73860692
    tools_remove_ = "remove"
    actionpoint_Object_group_cleaner = "Object_group_cleaner"
